# Group Diagrams
Welcome to the diagrams API. This API provides access to the diagrams service.

## diagrams [/diagrams]

### Get physical diagram [GET]

Returns a diagram.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (diagram, fixed)

## diagram details [/nodes/{type}]

+ Parameters
    + type: `physical` (enum[string]) - The type of the desired diagram.
        + Members
            + `physical`
            + `logical`

# Data Structures
## diagram (object)

+ nodes ([]diagramnode)
+ links ([]diagramlink)
