FORMAT: 1A
HOST: http://localhost:8080

# clay API

<!-- include(design.apib) -->
<!-- include(diagram.apib) -->
<!-- include(diagram_interface.apib) -->
<!-- include(diagram_link.apib) -->
<!-- include(diagram_meta.apib) -->
<!-- include(diagram_node.apib) -->
<!-- include(node.apib) -->
<!-- include(node_group.apib) -->
<!-- include(node_pv.apib) -->
<!-- include(node_type.apib) -->
<!-- include(port.apib) -->
<!-- include(segment.apib) -->
