# Group NodeTypes
Welcome to the node types API. This API provides access to the node types service.

## node types [/node_types]

### Create node type [POST]

Create a new node type

+ Request node type (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json
    + Attributes

        + name: NAME (string)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (node_type, fixed)

### Get node types [GET]

Returns a node type list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (node_type)

## node type details [/node_types/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired node type.
        + Members
            + `1`
            + `2`
            + `3`

### Get node type [GET]

Returns a node type.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (node_type, fixed)

### Update node type [PUT]

Update a node type.

+ Request node_type (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json
    + Attributes

        + name: NAME (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (node_type, fixed)

### Delete node type [DELETE]

Delete a node type.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 204

# Data Structures
## node_type (object)

+ id: *1* (number)
+ name: *NAME* (string)
