# Group NodePvs
Welcome to the node pvs API. This API provides access to the node pvs service.

## node pvs [/node_pvs]

### Create node pv [POST]

Create a new node pv

+ Request node pv (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json
    + Attributes

        + name: NAME (string)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (node_pv, fixed)

### Get node pvs [GET]

Returns a node pv list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (node_pv)

## node pv details [/node_pvs/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired node pv.
        + Members
            + `1`
            + `2`
            + `3`

### Get node pv [GET]

Returns a node pv.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (node_pv, fixed)

### Update node pv [PUT]

Update a node pv.

+ Request node_pv (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json
    + Attributes

        + name: NAME (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (node_pv, fixed)

### Delete node pv [DELETE]

Delete a node pv.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 204

# Data Structures
## node_pv (object)

+ id: *1* (number)
+ name: *NAME* (string)
