# Group Nodes
Welcome to the nodes API. This API provides access to the nodes service.

## nodes [/nodes]

### Create node [POST]

Create a new node

+ Request node (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json
    + Attributes

        + name: NAME (string)
        + node_type_id: 1 (number)
        + node_type (nodetype)
        + node_pv_id: 1 (number)
        + node_pv (nodepv)
        + remark: REMARK (string, nullable)
        + ports (array[port])
        + node_groups ([]nodegroup)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (node, fixed)

### Get nodes [GET]

Returns a node list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (node)

## node details [/nodes/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired node.
        + Members
            + `1`
            + `2`
            + `3`

### Get node [GET]

Returns a node.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (node, fixed)

### Update node [PUT]

Update a node.

+ Request node (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json
    + Attributes

        + name: NAME (string)
        + node_type_id: 1 (number)
        + node_type (nodetype)
        + node_pv_id: 1 (number)
        + node_pv (nodepv)
        + remark: REMARK (string, nullable)
        + ports (array[port])
        + node_groups ([]nodegroup)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (node, fixed)

### Delete node [DELETE]

Delete a node.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 204

# Data Structures
## node (object)

+ id: *1* (number)
+ name: *NAME* (string)
+ node_type_id: *1* (number)
+ node_type (nodetype)
+ node_pv_id: *1* (number)
+ node_pv (nodepv)
+ remark: *REMARK* (string, nullable)
+ ports (array[port])
+ node_groups ([]nodegroup)
