# Group Ports
Welcome to the ports API. This API provides access to the ports service.

## ports [/ports]

### Create port [POST]

Create a new port

+ Request port (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json
    + Attributes

        + node_id: 1 (number)
        + node (node)
        + name: NAME (string)
        + destination_port_id: 1 (number, nullable)
        + destination_port ()
        + mac_address: MACADDRESS (string, nullable)
        + ipv4_address: IPV4ADDRESS (string, nullable)
        + ipv4_prefix: 1 (number, nullable)
        + remark: REMARK (string, nullable)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (port, fixed)

### Get ports [GET]

Returns a port list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (port)

## port details [/ports/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired port.
        + Members
            + `1`
            + `2`
            + `3`

### Get port [GET]

Returns a port.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (port, fixed)

### Update port [PUT]

Update a port.

+ Request port (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json
    + Attributes

        + node_id: 1 (number)
        + node (node)
        + name: NAME (string)
        + destination_port_id: 1 (number, nullable)
        + destination_port ()
        + mac_address: MACADDRESS (string, nullable)
        + ipv4_address: IPV4ADDRESS (string, nullable)
        + ipv4_prefix: 1 (number, nullable)
        + remark: REMARK (string, nullable)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (port, fixed)

### Delete port [DELETE]

Delete a port.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.qb0C80aE+json

+ Response 204

# Data Structures
## port (object)

+ id: *1* (number)
+ node_id: *1* (number)
+ node (node)
+ name: *NAME* (string)
+ destination_port_id: *1* (number, nullable)
+ destination_port ()
+ mac_address: *MACADDRESS* (string, nullable)
+ ipv4_address: *IPV4ADDRESS* (string, nullable)
+ ipv4_prefix: *1* (number, nullable)
+ remark: *REMARK* (string, nullable)
